from enum import Enum


class ErrorCode(str, Enum):
    SHARE_NOT_FOUND = "SHARE_NOT_FOUND"
    SHARE_TOKEN_NOT_FOUND = "SHARE_TOKEN_NOT_FOUND"
    PROJECT_ALREADY_SHARED = "PROJECT_ALREADY_SHARED"
    CANNOT_SHARE_WITH_SELF = "CANNOT_SHARE_WITH_SELF"
    INVALID_SHARE_TOKEN = "INVALID_SHARE_TOKEN"
    ACCESS_DENIED = "ACCESS_DENIED"


# Share status constants
SHARE_TOKEN_LENGTH = 32
