# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:22 AS build-stage

# Install pnpm
RUN npm install -g pnpm@latest-10

# Install Angular CLI
RUN npm install -g @angular/cli@latest

WORKDIR /app
